services:
  - type: web
    name: resoneo_app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ANTHROPIC_API_KEY
        value: laasba
      - key: PORT
        value: 10000
